title: Blog
description: Halaman ini berisi artikel dari Tim Transport for Bandung
remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes
baseurl: /blog 
url: https://transportforbandung.github.io
